### ISSUE TITLE
Issues on Firefox 42.0

### ISSUE THREAD

**Issue by hasB4K** [5digits/dactyl#95]
Hello,

It seems the git version of Pentadactyl doesn't work on Firefox 42.0.
I have changed the variable 'em:maxVersion' to "42.*" in the file 'pentadactyl/install.rdf' and it works.

The maintainer of the package 'pentadactyl-git' on archlinux has done the same thing:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pentadactyl-git

However, I have noticed that the commands `:help` and `:helpall` seems to be broken. I don't know if it is due to the update or not though.

EDIT:
I use Arch Linux.
When I type the ':help' command, I have this error:
`Sorry, help file "intro" not found`

EDIT2:
It seems that the `:help` command makes firefox unable to be exited normally, the process is still running in background when you close firefox normally, you have to kill the process yourself. Thanks @duguyipiao for the report.

Best regards,

**Comment by jdevelop** [comment]
for me, pressing ":" pops up some web developer console rather than pentadactyl command prompt. Latest version fron git, with version changes in install.rdf

**Comment by betaveros** [comment]
I also cloned the latest version ( https://github.com/5digits/dactyl/commit/fb1355242145a4227d12ccec52ac2f69d78574ab ) and bumped the version number in install.rdf and it works fine for me on 42.0, for some reason; I don't see either of the above issues. I'm on Mac OS X 10.10.5. What OSes are y'all using?

**Comment by hasB4K** [comment]
I use Arch Linux.

**Comment by linduxed** [comment]
I use Arch and don't have a problem with `:`. On the other hand, I can no longer get up the right-click menu.

**Comment by duguyipiao** [comment]
Same here with Ubuntu 14.04 and Firefox 42. 
`:help` gives `Sorry, help file "intro" not found`

**Comment by mario-grgic** [comment]
Are you installing this on unbranded version of Firefox 42 or regular release Firefox 42? If release version, then how did you work around the signing requirement?

**Comment by vyp** [comment]
@mario-grgic (apparently) firefox 42 does not require signing yet: https://github.com/5digits/dactyl/issues/79#issuecomment-153760355

**Comment by maturano** [comment]
From the commit fb13552

```
:version
Pentadactyl 1.2pre running on:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0
```

Ubuntu 14.04, Firefox from repositories, all working for now

**Comment by oddRaven** [comment]
Firefox 42 says that Pentadactyl is incompatible. Tried both the normal and nightly builds.

**Comment by vyp** [comment]
@oddRaven I think that's because of the `maxVersion` metadata: #93.

**Comment by specious** [comment]
```patch
```

**Comment by specious** [comment]
Same here on OS X 10.11, after I updated Firefox to 42.0.  Like @hasB4K, it installs after this:

```diff
diff --git a/pentadactyl/install.rdf b/pentadactyl/install.rdf
index 869f130..3a4cc97 100644
--- a/pentadactyl/install.rdf
+++ b/pentadactyl/install.rdf
@@ -32,7 +32,7 @@
             <Description
                 em:id="{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
                 em:minVersion="31.0"
-                em:maxVersion="41.*"/>
+                em:maxVersion="42.*"/>
         </em:targetApplication>
     </Description>
 </RDF>
```

`:help` and `:helpall` are also broken for me:

```
:help
Sorry, help file "intro" not found

:helpall
Sorry, help file "all" not found
```

**Comment by duguyipiao** [comment]
@hasB4K @specious Does `:help` make your firefox unable to exit normally. In my computer,  after `:help` I can close my firefox window, but the process of firefox does not end. I have to kill the process, before I can restart firefox .

Runing `firefox -pentadactyl '+u NONE'` gives
```bash
pentadactyl: All dactyl modules destroyed
pentadactyl: bootstrap: shutdown shutdown
```

**Comment by hasB4K** [comment]
@duguyipiao I have no issues either with `:help` or with the command `firefox -pentadactyl '+u NONE'`. On what OS are you?

**Comment by polyzen** [comment]
+1 for the :help issue

These really should be separate issues, shouldn't they?

**Comment by duguyipiao** [comment]
@polyzen I think it is enough, if @hasB4K adds it to the issue description.

**Comment by polyzen** [comment]
@duguyipiao, for some reason I thought there were like 3 issues going on here. I see:
1) `:help` issue (confirmed)
2) `firefox -pentadactyl '+u NONE'` issue (cannot reproduce)

**Comment by duguyipiao** [comment]
@polyzen, Maybe my expression mislead you. These are the same issue. I have reedited my previous post.

**Comment by hotroddeathtoll** [comment]
I've built the xpi per the recommendation, "42.*".  No problems with the build but the install doesn't do anything.  FF actually thinks its enabled too but not working, i.e., no status bar, command line, nada, nothing...  Built in cygwin on a win 7 box, never had issues before.  Thoughts??

**Comment by polyzen** [comment]
@duguyipiao, ahhh I see now :)

**Comment by hrzhu** [comment]
I don't have the help issue on my Xubuntu 14.04 installation but have it on my Xubutu 16.04 installation. They both run Firefox 42.

**Comment by PTNobel** [comment]
calling `:downloads` gives the following error:

    resource://dactyl/downloads.jsm: 234: TypeError: calling a builtin Map constructor without new is forbidden

**Comment by hrzhu** [comment]
^
this has probably been fixed by 6882834.

**Comment by sillyousu** [comment]
@hrzhu 
It doesn't fix this bug. I have this problem in e3c3748511ff6dfa8d917cbba04eaa7d94ad461c

**Comment by polyzen** [comment]
:downloads works here

**Comment by willsALMANJ** [comment]
I didn't test them individually but either bc9eb79fb310dac1ea8dd304bac4db996c51e6d8 or 65725c95164c6da1fe5bedbeafa651c06d08b72e fixed this issue.

**Comment by willsALMANJ** [comment]
Actually, I take it back. I am still having this issue with the latest commit. I was testing with a new profile and `:help` worked in that case, but when I went back to my old profile the problem was still there. Someone else should test this. It seems like the problem might related to a profile setting.

**Comment by polyzen** [comment]
:help works. It's about time this gets closed, yeh? ;p
